DROP TABLE IF EXISTS posts;
CREATE TABLE posts
(
  id        INT AUTO_INCREMENT PRIMARY KEY,
  title     VARCHAR(250) NOT NULL,
  body      VARCHAR(250) NOT NULL,
  author_id INT
);

DROP TABLE IF EXISTS authors;
CREATE TABLE authors
(
  id   INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS tags;
CREATE TABLE tags
(
  id   INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS post_tags;
CREATE TABLE post_tags
(
  id      INT AUTO_INCREMENT PRIMARY KEY,
  post_id INT,
  tag_id  INT
);